[general]
live_config_reload = false
ipc_socket = false

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 120, lines = 40 }
decorations = "full"

[window.padding]
x = 5
y = 5

[font]
size = 13

[colors.primary]
background = "#0A0A0A"  # Matches Neovim & VS Code
foreground = "#E0E0E0"  # Light gray text

[cursor]
style = { shape = "Beam", blinking = "Never" }

[colors.selection]
text = "CellForeground"
background = "#222222"  # Slightly lighter selection

# ANSI Colors
[colors.normal]
black = "#121212"
red = "#FF5555"
green = "#50FA7B"
yellow = "#F1FA8C"
blue = "#BD93F9"
magenta = "#FF79C6"
cyan = "#8BE9FD"
white = "#BBBBBB"

[colors.bright]
black = "#555555"
red = "#FF6E67"
green = "#5AF78E"
yellow = "#F4F99D"
blue = "#CAA9FA"
magenta = "#FF92D0"
cyan = "#9AEDFE"
white = "#FFFFFF"

[font.normal]
family = "JetBrainsMono Nerd Font"  # Change if using a different font
style = "Regular"
